#' @title MetaboMap
#'
#' @description Maps multiple identifiers from a study data frame to a reference data frame by iterating through corresponding identifier and study column pairs. Ensures data integrity, applies mapping functions, and adds confidence levels and labels.
#'
#' @param df_study A data frame representing the study data containing metabolites information to be processed.
#' @param study_cols A column name or a vector of column names in `df_study` corresponding to identifiers to be mapped.
#' @param identifiers An identifier or a vector of identifiers to be mapped; must be the same length and same order as `study_cols`. It can takes values c("HMDB","NAME","KEGG","CHEBI","INCHIKEY")
#' @param df_reference Dataframe generated by the function hmdbextract().
#' @param details A boolean- Default Value is FALSE. TRUE allows to have additional details for each mapping identifier.
#' @param original_name The original name of the data or dataset for labeling purposes. Default value is "study".
#'
#' @return A data frame object containing the mapped identifiers with confidence levels.
#' @examples
#' # Example usage:
#' study_data <- data.frame(metabolite_name=c("M1","M2"),id1 = c(1, 2), id2 = c("A", "B"))
#' reference_data <- data.frame(ref_id = c(1, 2), name = c("X", "Y"))
#' result <- MetaboMap(
#'   df_study = study_data,
#'   study_cols = c("id1", "id2"),
#'   identifiers = c("ref_id", "name"),
#'   df_reference = reference_data,
#'   details = FALSE,
#'   original_name = "metabolite_name"
#' )
#' @export
MetaboMap <- function(df_study, study_cols, identifiers ,df_reference,details=FALSE,original_name="" ) {


  # Ensure all vectors are of the same length
  if (length(identifiers) != length(study_cols) ) {
    stop("Identifiers and study_cols must have the same length!")
  }

  # Loop through identifiers, using their corresponding columns
  for (i in seq_along(identifiers)) {
    identifier <- identifiers[i]
    col_study <- study_cols[i]


    cat("Processing identifier:", identifier, "\n")
    cat("Using study column:", col_study)

    # Call the map_metab function for this identifier and columns
    df_study <- map_unique_identifier(df_study, col_study,df_reference, identifier)
  }


  df_study<-mapper_confidence_level(df_study)

  df_study<-final_label_dataframe(df_study, details=details,original_name=original_name)
  return(df_study)
}





