#' @title MetaboMap
#'
#' @description Matches one or multiple metabolites identifiers of interest between the study dataframe and the generated reference dataframe from HMDB.
#'
#' @param df_study A data frame containing metabolite information from the study, where each row corresponds to a metabolite and each column contain one identifier.
#' @param study_cols A column name or a vector of column names in `df_study` corresponding to identifiers to be mapped.
#' @param identifiers An identifier or a vector of identifiers to be mapped; must be the same length and same order as `study_cols`. It can takes values c("HMDB","NAME","KEGG","CHEBI","INCHIKEY")
#' @param df_reference Dataframe generated by the function hmdbextract().
#' @param details A boolean- Default Value is FALSE. TRUE allows to have additional details for each mapping identifier.
#' @param original_colname A column name in `df_study` containing the original metabolites label in the study
#'
#' @return A data frame object containing the mapped identifiers with confidence levels.
#' @examples
# Example usage:
#' study_data <- data.frame(
#'   metabolite_name = c("1-Methylhistidine", "2-Ketobutyric acid"),
#'   HMDB_id = c("HMDB0000001", "HMDB0000005")
#' )
#'
#' reference_data <- data.frame(
#'   accession = c("HMDB0000001", "HMDB0000002", "HMDB0000005"),
#'   name = c("1-Methylhistidine", "1,3-Diaminopropane", "2-Ketobutyric acid"),
#'   all_HMDBs = c(
#'     "HMDB0000001|HMDB00001|HMDB0004935",
#'     "HMDB0000002|HMDB00002",
#'     "HMDB0000005|HMDB00005|HMDB0006544"
#'   ),
#'   all_names = c(
#'     "1-Methylhistidine|Pi-methylhistidine|",
#'     "1,3-Diaminopropane|1,3-Propanediamine|1,3-Propylenediamine",
#'     "2-Ketobutyric acid|2-Ketobutanoic acid|2-Oxobutyric acid"
#'   )
#' )
#'
#' result <- MetaboMap(
#'   df_study = study_data,
#'   study_cols = c("metabolite_name", "HMDB_id"),
#'   identifiers = c("NAME", "HMDB"),
#'   df_reference = reference_data,
#'   details = FALSE,
#'   original_colname = "metabolite_name"
#' )
#' @export
MetaboMap <- function(df_study, study_cols, identifiers ,df_reference,details=FALSE,original_colname) {


  # Ensure all vectors are of the same length
  if (length(identifiers) != length(study_cols) ) {
    stop("Identifiers and study_cols must have the same length!")
  }

  # Ensure that identifiers are correctly given in the input
  valid_identifiers <- c("HMDB", "NAME", "KEGG", "CHEBI", "INCHIKEY")
  invalid_identifiers <- setdiff(identifiers, valid_identifiers)
  if (length(invalid_identifiers) > 0) {
    stop(paste("The following identifiers are invalid:",
               paste(invalid_identifiers, collapse = ", "),
               "\nValid options are:", paste(valid_identifiers, collapse = ", ")))
  }

  # Ensure that the study_cols exist
  missing_study_cols <- setdiff(study_cols, colnames(df_study))
  if (length(missing_study_cols) > 0) {
    stop(paste("The following columns are missing in the study data frame:",
               paste(missing_study_cols, collapse = ", ")))
  }
    # Ensure that df_reference exists
    if (is.null(df_reference)) {
      stop("Reference data frame is missing or NULL. To produce the reference data frame, please run hmdbextract function to generate it.")
    }

  # Ensure that study dataframes exists
  if (is.null(df_study)) {
    stop("Study data frame is missing or NULL.")
  }



  # Loop through identifiers, using their corresponding columns
  for (i in seq_along(identifiers)) {
    identifier <- identifiers[i]
    col_study <- study_cols[i]

    # Check if any of the separation characters are present
  if(identifier!="NAME"){
    if (any(grepl("[,;/|]", df_study[[col_study]]))) {
      warning("Warning: Separation character(s) found in the column. Ensure to have one ID per identifier per row.")
    }
  }

    if(identifier=="NAME"){
      if (any(grepl("[/|]", df_study[[col_study]]))) {
        warning("Warning: Separation character(s) found in the column ",col_study,". Ensure to have one ID per identifier per row.")
      }
    }


    cat("Processing identifier:", identifier, "\n")
    cat("Using study column:", col_study,"\n")

    # Call the map_metab function for this identifier and columns
    df_study <- map_unique_identifier(df_study, col_study,df_reference, identifier)
  }


  df_study<-mapper_confidence_level(df_study)

  df_study<-final_label_dataframe(df_study,study_cols=study_cols, details=details,original_colname)
  return(df_study)

}





